version: '3'

services:
  meili:
    image: getmeili/meilisearch
    environment:
      - MEILI_ENV=development
      - MEILI_NO_ANALYTICS=true
    ports:
      - 7700:7700
    volumes:
      - ./meili_data:/meili_data
